name: pr

on:
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
         - 11-alpine-amd64
         - 11-alpine-arm64
         - 17-alpine-amd64
         - 17-alpine-arm64
    steps:
     - uses: actions/checkout@v3
     - run: make build-${{ matrix.image }}
