name: pr

on:
  pull_request:
    branches: [master]

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - 21-alpine-amd64
          - 21-alpine-arm64
          - 17-alpine-amd64
          - 17-alpine-arm64
    steps:
     - uses: actions/checkout@v3
     - name: Install latest docker-ce version
       uses: ./.github/actions/install-latest-docker-version
     - run: make build-${{ matrix.image }}
